== Test suite
This application tests the scenarios of restaurant-scoring-service and validates if the functionalities of the service
are working as expected

It uses https://cucumber.io/[Cucumber] - a Behaviour driven development framework to test the features. Behaviours are
recorded in https://cucumber.io/docs/gherkin/[Gherkin] format in feature files. Each Gherkin scenario consists of multiple steps
which will be in plain English and can be easily understood by anyone. Implementations of these
Gherkin steps which are written in Java does the testing in the backend.

For testing restaurant-scoring-service, we need to test all the endpoints exposed by passing
request body and authorization header. To make Rest calls, https://rest-assured.io/[RestAssured] library is used

Junit Assertions are used for validating the actual response with the expected result which is stored under src/main/resources/iofiles

=== Execution Steps
- Execute mvn test for running the tests
- CucumberTestRunner class will be triggered. Features files are supplied as CucumberOptions in this class
- All feature files available in the path will be executed sequentially
- This application is configured to produce HTML and XML reports
- Check in target/cucumber/index.html and target/cucumber-reports/cucumber.xml for reports

=== Reports

